### PR TITLE
Add cygwin build to appveyor

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by evanmiller** [comment]
Thanks

**Comment by evanmiller** [comment]
Hi, msys2 has been failing lately with `warning: ISO C does not support the 'I64' ms_printf length modifier [-Wformat=]`. Any ideas?

https://ci.appveyor.com/project/evanmiller/readstat/build/job/9fw0q5241pise4hm

**Comment by davidanthoff** [comment]
I think you fixed this already, right?

**Comment by evanmiller** [comment]
Yes `-Wno-pedantic-ms-format` got rid of the error. Not sure why it's only on msys2 but the build is back to passing. Thanks.

**Pull request merged**
