### PR TITLE
make xpt v8 SAS-readable

### PR DESCRIPTION
**Pull request by reikoch**
Hi Evan!

I propose very few changes to make xpt version 8 files SAS-readable. On some examples ReadStat now produces readable files by setting format and informat name to blank (not nulls).

Given https://documentation.sas.com/?docsetId=movefile&docsetTarget=p0ld1i106e1xm7n16eefi7qgj8m9.htm&docsetVersion=9.4&locale=en I would be willing to improve on this PR with target to preserve also long variable names, formats, and informats. Would that be of interest to you?

### CODE REVIEW

**Comment by evanmiller** [comment]
Hi, thank you for the contribution. Additional fixes to improve compatibility with SAS would be very welcome.

**Comment by reikoch** [comment]
Will do in the next days!

**Comment by evanmiller** [comment]
When you do, please point the PR at the `dev` branch rather than `master`. Thanks.

**Comment by reikoch** [comment]
This is how good it gets right now. Table labels are not written to xpt v8 files, that is not top priority. Table labels are not read or written for SAS datasets. reading sas7bdat is reading table name but declares it file_label in ctx. Example dataset dates.sas7bdat in https://github.com/reikoch/testfiles display file_label 'dataset label for the dates test dataset just before variable formats are stored.

Ready for merge if OK; can help with table label if so wished.

**Comment by evanmiller** [comment]
The automated tests indicate a segmentation fault. This will need to be fixed before merging.

**Comment by reikoch** [comment]
OK Evan,
let's try to get this version merged in. It creates SAS-readable xpt v8 files, though table name and dates/times/datetimes specifications are dropped.

**Comment by evanmiller** [comment]
Done! Feel free to open other PRs with additional fixes.

**Pull request merged**
