### PR TITLE
Add option to disable spawnv define

### PR DESCRIPTION
**Pull request by JorisGoosen**
Helps UCRT mingw users workaround the problem mentioned in https://github.com/WizardMac/ReadStat/issues/300

### CODE REVIEW

**Comment by JorisGoosen** [comment]
@evanmiller ?

**Comment by evanmiller** [comment]
I would prefer to have the script detect the platform and do the right behavior, rather than add an option.

**Comment by JorisGoosen** [comment]
> I would prefer to have the script detect the platform and do the right behavior, rather than add an option.

Fair enough, Ill have a look

**Comment by JorisGoosen** [comment]
The new configure doesnt require a manual option anymore, I tested it on Mingw x64 and Mingw UCRT x64 and it now configures and compiles on both without a hitch

**Comment by evanmiller** [comment]
There's probably a cleaner way to do this with autconf (see https://stackoverflow.com/questions/46704731/check-value-of-c-define-with-autoconf) but this seems good enough for now, thanks

**Comment by JorisGoosen** [comment]
Ah yeah that SO answer looks cleaner for sure, but thanks for merging it anyway. It will make our build process much smoother.

**Pull request merged**
